version: '2'

services:
  image_sync:
    image: 'image_sync:latest'
    env_file:
      - '.env'
    volumes:
      - 'image_sync:/usr/src/app'
      - '${LOCAL_DESTINATION}:${CONTAINER_DESTINATION}'
      - '${LOCAL_SOURCE}:${CONTAINER_SOURCE}'

volumes:
  image_sync:

